1) запускаем приложение докера на фоне
2) docker compose build - собираем
3) docker compose up - запускаем

указываем на каком образе будет работать контейнер
FROM node:12.13-alpine

рабочаем директория, уже внутри контейнера
WORKDIR /app

копируем в рабочую директорию package и package-lock в рабочую директорию
COPY package*.json ./

устанавливаем все зависимости
RUN npm install

копируем все файлы
COPY . .

COPY ./dist ./dist

запускаем в режиме "для разработки"
CMD ["npm", "run", "start:dev"]